# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMNavigationController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TMNavigationController

  target 'TMNavigationControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMNavigationControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SDCycleScrollView'

end
